<?php

namespace Database\Seeders;

use App\Models\Task;
use App\Models\Empresa;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TaskSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Crear primera empresa si no existe
        $empresa1 = Empresa::firstOrCreate(
            ['nombre' => 'Empresa Principal'],
            [
                'email' => 'info@empresa.com',
                'telefono' => '912345678'
            ]
        );

        // Crear segunda empresa
        $empresa2 = Empresa::firstOrCreate(
            ['nombre' => 'Empresa Secundaria'],
            [
                'email' => 'info@empresa2.com',
                'telefono' => '913456789'
            ]
        );

        $tasks = [
            // Tareas para la primera empresa
            [
                'titulo' => 'Reparación de Tejado',
                'referencia' => 'REP-2025-001',
                'fotos' => ['tejado1.jpg', 'tejado2.jpg'],
                'documentos' => ['presupuesto.pdf', 'contrato.pdf'],
                'precio' => 2500.00,
                'descripcion' => 'Reparación de goteras y tejas rotas en tejado residencial',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-03-15',
                'fecha_finalizado' => null,
                'provincia' => 'Madrid',
                'localidad' => 'Alcobendas',
                'direccion' => 'Calle Mayor 123',
                'postal' => '28100',
                'pais' => 'España',
                'latitud' => 40.5478963,
                'longitud' => -3.6425841,
                'telefono' => '634567890',
                'email' => 'cliente1@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Aire Acondicionado',
                'referencia' => 'INS-2025-002',
                'fotos' => ['ac1.jpg', 'ac2.jpg'],
                'documentos' => ['manual.pdf'],
                'precio' => 1200.00,
                'descripcion' => 'Instalación de sistema de aire acondicionado split',
                'estado' => 'curso',
                'fecha_prevista' => '2025-02-28',
                'fecha_finalizado' => null,
                'provincia' => 'Barcelona',
                'localidad' => 'Hospitalet',
                'direccion' => 'Avenida Catalunya 45',
                'postal' => '08901',
                'pais' => 'España',
                'latitud' => 41.3595633,
                'longitud' => 2.1014742,
                'telefono' => '612345678',
                'email' => 'cliente2@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Pintura Interior Vivienda',
                'referencia' => 'PIN-2025-003',
                'fotos' => ['sala1.jpg', 'dormitorio1.jpg'],
                'documentos' => ['contrato_pintura.pdf'],
                'precio' => 1800.00,
                'descripcion' => 'Pintura completa de vivienda 90m2',
                'estado' => 'finalizado',
                'fecha_prevista' => '2025-01-20',
                'fecha_finalizado' => '2025-01-18',
                'provincia' => 'Valencia',
                'localidad' => 'Paterna',
                'direccion' => 'Calle San Antonio 78',
                'postal' => '46980',
                'pais' => 'España',
                'latitud' => 39.5018425,
                'longitud' => -0.4416741,
                'telefono' => '654789123',
                'email' => 'cliente3@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Reforma Baño Completo',
                'referencia' => 'REF-2025-004',
                'fotos' => ['baño_antes.jpg', 'proceso.jpg'],
                'documentos' => ['presupuesto_baño.pdf', 'planos.pdf'],
                'precio' => 4500.00,
                'descripcion' => 'Reforma integral de baño incluyendo sanitarios y azulejos',
                'estado' => 'curso',
                'fecha_prevista' => '2025-03-30',
                'fecha_finalizado' => null,
                'provincia' => 'Sevilla',
                'localidad' => 'Dos Hermanas',
                'direccion' => 'Plaza España 12',
                'postal' => '41700',
                'pais' => 'España',
                'latitud' => 37.2829752,
                'longitud' => -5.9216657,
                'telefono' => '678912345',
                'email' => 'cliente4@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Paneles Solares',
                'referencia' => 'SOL-2025-005',
                'fotos' => ['techo1.jpg', 'paneles1.jpg'],
                'documentos' => ['proyecto_tecnico.pdf'],
                'precio' => 8500.00,
                'descripcion' => 'Instalación de sistema fotovoltaico 5kW',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-04-15',
                'fecha_finalizado' => null,
                'provincia' => 'Málaga',
                'localidad' => 'Torremolinos',
                'direccion' => 'Avenida del Mar 234',
                'postal' => '29620',
                'pais' => 'España',
                'latitud' => 36.6246487,
                'longitud' => -4.4989716,
                'telefono' => '645123789',
                'email' => 'cliente5@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Limpieza de Fachada',
                'referencia' => 'LIM-2025-006',
                'fotos' => ['fachada_sucia.jpg', 'proceso_limpieza.jpg'],
                'documentos' => ['permiso_ayuntamiento.pdf'],
                'precio' => 1200.00,
                'descripcion' => 'Limpieza de fachada con chorro de arena',
                'estado' => 'finalizado',
                'fecha_prevista' => '2025-02-10',
                'fecha_finalizado' => '2025-02-08',
                'provincia' => 'Zaragoza',
                'localidad' => 'Zaragoza',
                'direccion' => 'Calle Alfonso 56',
                'postal' => '50003',
                'pais' => 'España',
                'latitud' => 41.6521342,
                'longitud' => -0.8809389,
                'telefono' => '689234567',
                'email' => 'cliente6@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Suelo Radiante',
                'referencia' => 'RAD-2025-007',
                'fotos' => ['suelo1.jpg', 'instalacion1.jpg'],
                'documentos' => ['especificaciones.pdf'],
                'precio' => 5600.00,
                'descripcion' => 'Instalación de suelo radiante en vivienda 120m2',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-05-20',
                'fecha_finalizado' => null,
                'provincia' => 'Bilbao',
                'localidad' => 'Getxo',
                'direccion' => 'Calle Puerto 89',
                'postal' => '48930',
                'pais' => 'España',
                'latitud' => 43.3526467,
                'longitud' => -3.0134871,
                'telefono' => '678234567',
                'email' => 'cliente7@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Cambio Ventanas PVC',
                'referencia' => 'VEN-2025-008',
                'fotos' => ['ventanas_viejas.jpg', 'ventanas_nuevas.jpg'],
                'documentos' => ['certificado_eficiencia.pdf'],
                'precio' => 3200.00,
                'descripcion' => 'Sustitución de ventanas antiguas por PVC de doble acristalamiento',
                'estado' => 'curso',
                'fecha_prevista' => '2025-03-25',
                'fecha_finalizado' => null,
                'provincia' => 'Alicante',
                'localidad' => 'Benidorm',
                'direccion' => 'Avenida Mediterráneo 123',
                'postal' => '03500',
                'pais' => 'España',
                'latitud' => 38.5410566,
                'longitud' => -0.1224937,
                'telefono' => '634567891',
                'email' => 'cliente8@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Piscina',
                'referencia' => 'PIS-2025-009',
                'fotos' => ['terreno.jpg', 'excavacion.jpg'],
                'documentos' => ['proyecto_piscina.pdf', 'permisos.pdf'],
                'precio' => 15000.00,
                'descripcion' => 'Construcción e instalación de piscina 8x4m',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-06-30',
                'fecha_finalizado' => null,
                'provincia' => 'Murcia',
                'localidad' => 'Cartagena',
                'direccion' => 'Calle del Mar 45',
                'postal' => '30201',
                'pais' => 'España',
                'latitud' => 37.6019028,
                'longitud' => -0.9835975,
                'telefono' => '678912346',
                'email' => 'cliente9@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Reforma Cocina',
                'referencia' => 'COC-2025-010',
                'fotos' => ['cocina_antigua.jpg', 'diseño_3d.jpg'],
                'documentos' => ['presupuesto_detallado.pdf'],
                'precio' => 7800.00,
                'descripcion' => 'Reforma integral de cocina con electrodomésticos',
                'estado' => 'curso',
                'fecha_prevista' => '2025-04-10',
                'fecha_finalizado' => null,
                'provincia' => 'Granada',
                'localidad' => 'Granada',
                'direccion' => 'Calle Recogidas 67',
                'postal' => '18002',
                'pais' => 'España',
                'latitud' => 37.1734529,
                'longitud' => -3.5981468,
                'telefono' => '645789123',
                'email' => 'cliente10@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Domótica',
                'referencia' => 'DOM-2025-011',
                'fotos' => ['dispositivos.jpg', 'control.jpg'],
                'documentos' => ['manual_usuario.pdf'],
                'precio' => 4200.00,
                'descripcion' => 'Instalación sistema domótico completo',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-05-15',
                'fecha_finalizado' => null,
                'provincia' => 'Madrid',
                'localidad' => 'Pozuelo',
                'direccion' => 'Avenida Europa 89',
                'postal' => '28223',
                'pais' => 'España',
                'latitud' => 40.4380638,
                'longitud' => -3.8196804,
                'telefono' => '678234568',
                'email' => 'cliente11@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Jardín Vertical',
                'referencia' => 'JAR-2025-012',
                'fotos' => ['pared.jpg', 'plantas.jpg'],
                'documentos' => ['sistema_riego.pdf'],
                'precio' => 3600.00,
                'descripcion' => 'Instalación de jardín vertical en terraza',
                'estado' => 'finalizado',
                'fecha_prevista' => '2025-02-28',
                'fecha_finalizado' => '2025-02-25',
                'provincia' => 'Barcelona',
                'localidad' => 'Sant Cugat',
                'direccion' => 'Rambla del Celler 45',
                'postal' => '08172',
                'pais' => 'España',
                'latitud' => 41.4720944,
                'longitud' => 2.0865982,
                'telefono' => '634567892',
                'email' => 'cliente12@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Impermeabilización Terraza',
                'referencia' => 'IMP-2025-013',
                'fotos' => ['goteras.jpg', 'tela_asfaltica.jpg'],
                'documentos' => ['garantia.pdf'],
                'precio' => 2800.00,
                'descripcion' => 'Impermeabilización de terraza 40m2',
                'estado' => 'curso',
                'fecha_prevista' => '2025-03-20',
                'fecha_finalizado' => null,
                'provincia' => 'Valencia',
                'localidad' => 'Torrent',
                'direccion' => 'Calle Mayor 234',
                'postal' => '46900',
                'pais' => 'España',
                'latitud' => 39.4366523,
                'longitud' => -0.4654359,
                'telefono' => '678912347',
                'email' => 'cliente13@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Punto Recarga',
                'referencia' => 'REC-2025-014',
                'fotos' => ['parking.jpg', 'cargador.jpg'],
                'documentos' => ['certificado_instalacion.pdf'],
                'precio' => 1600.00,
                'descripcion' => 'Instalación punto de recarga vehículo eléctrico',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-04-05',
                'fecha_finalizado' => null,
                'provincia' => 'Sevilla',
                'localidad' => 'Sevilla',
                'direccion' => 'Calle Betis 78',
                'postal' => '41001',
                'pais' => 'España',
                'latitud' => 37.3826719,
                'longitud' => -5.9962034,
                'telefono' => '645789124',
                'email' => 'cliente14@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Cambio Caldera Gas',
                'referencia' => 'CAL-2025-015',
                'fotos' => ['caldera_vieja.jpg', 'caldera_nueva.jpg'],
                'documentos' => ['certificado_gas.pdf'],
                'precio' => 2200.00,
                'descripcion' => 'Sustitución de caldera antigua por modelo condensación',
                'estado' => 'finalizado',
                'fecha_prevista' => '2025-02-15',
                'fecha_finalizado' => '2025-02-14',
                'provincia' => 'Málaga',
                'localidad' => 'Marbella',
                'direccion' => 'Avenida Ricardo Soriano 156',
                'postal' => '29601',
                'pais' => 'España',
                'latitud' => 36.5097593,
                'longitud' => -4.8861836,
                'telefono' => '678234569',
                'email' => 'cliente15@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Insonorización Local',
                'referencia' => 'INS-2025-016',
                'fotos' => ['local1.jpg', 'paneles.jpg'],
                'documentos' => ['estudio_acustico.pdf'],
                'precio' => 6500.00,
                'descripcion' => 'Insonorización completa de local comercial',
                'estado' => 'curso',
                'fecha_prevista' => '2025-04-30',
                'fecha_finalizado' => null,
                'provincia' => 'Zaragoza',
                'localidad' => 'Zaragoza',
                'direccion' => 'Paseo Independencia 89',
                'postal' => '50001',
                'pais' => 'España',
                'latitud' => 41.6517623,
                'longitud' => -0.8817521,
                'telefono' => '634567893',
                'email' => 'cliente16@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Reforma Escalera',
                'referencia' => 'ESC-2025-017',
                'fotos' => ['escalera_antigua.jpg', 'diseño.jpg'],
                'documentos' => ['planos_escalera.pdf'],
                'precio' => 4800.00,
                'descripcion' => 'Renovación completa de escalera interior',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-05-10',
                'fecha_finalizado' => null,
                'provincia' => 'Bilbao',
                'localidad' => 'Bilbao',
                'direccion' => 'Gran Vía 45',
                'postal' => '48001',
                'pais' => 'España',
                'latitud' => 43.2630018,
                'longitud' => -2.9350039,
                'telefono' => '678912348',
                'email' => 'cliente17@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Pérgola',
                'referencia' => 'PER-2025-018',
                'fotos' => ['terraza1.jpg', 'pergola.jpg'],
                'documentos' => ['permiso_comunidad.pdf'],
                'precio' => 3900.00,
                'descripcion' => 'Instalación de pérgola bioclimática',
                'estado' => 'curso',
                'fecha_prevista' => '2025-03-28',
                'fecha_finalizado' => null,
                'provincia' => 'Alicante',
                'localidad' => 'Alicante',
                'direccion' => 'Avenida Alfonso X 123',
                'postal' => '03004',
                'pais' => 'España',
                'latitud' => 38.3459963,
                'longitud' => -0.4906855,
                'telefono' => '645789125',
                'email' => 'cliente18@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Cambio Suelo Parquet',
                'referencia' => 'PAR-2025-019',
                'fotos' => ['suelo_viejo.jpg', 'parquet.jpg'],
                'documentos' => ['garantia_material.pdf'],
                'precio' => 4200.00,
                'descripcion' => 'Instalación de parquet en vivienda 100m2',
                'estado' => 'finalizado',
                'fecha_prevista' => '2025-02-20',
                'fecha_finalizado' => '2025-02-18',
                'provincia' => 'Murcia',
                'localidad' => 'Murcia',
                'direccion' => 'Gran Vía 67',
                'postal' => '30004',
                'pais' => 'España',
                'latitud' => 37.9845734,
                'longitud' => -1.1307897,
                'telefono' => '678234570',
                'email' => 'cliente19@email.com',
                'empresa_id' => $empresa1->id,
            ],
            [
                'titulo' => 'Instalación Toldo Motorizado',
                'referencia' => 'TOL-2025-020',
                'fotos' => ['fachada.jpg', 'toldo.jpg'],
                'documentos' => ['manual_control.pdf'],
                'precio' => 1900.00,
                'descripcion' => 'Instalación de toldo motorizado con sensor de viento',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-04-15',
                'fecha_finalizado' => null,
                'provincia' => 'Granada',
                'localidad' => 'Granada',
                'direccion' => 'Calle Reyes Católicos 90',
                'postal' => '18001',
                'pais' => 'España',
                'latitud' => 37.1773363,
                'longitud' => -3.5985571,
                'telefono' => '634567894',
                'email' => 'cliente20@email.com',
                'empresa_id' => $empresa1->id,
            ],
            // Tareas para la segunda empresa
            [
                'titulo' => 'Instalación Fibra Óptica',
                'referencia' => 'FIB-2025-001',
                'fotos' => ['fibra1.jpg', 'fibra2.jpg'],
                'documentos' => ['contrato_fibra.pdf'],
                'precio' => 1200.00,
                'descripcion' => 'Instalación de fibra óptica en edificio de oficinas',
                'estado' => 'curso',
                'fecha_prevista' => '2025-03-20',
                'fecha_finalizado' => null,
                'provincia' => 'Barcelona',
                'localidad' => 'Sant Cugat',
                'direccion' => 'Avenida Empresarial 45',
                'postal' => '08172',
                'pais' => 'España',
                'latitud' => 41.4720944,
                'longitud' => 2.0865982,
                'telefono' => '678123456',
                'email' => 'oficinas@empresa2.com',
                'empresa_id' => $empresa2->id,
            ],
            [
                'titulo' => 'Mantenimiento Servidores',
                'referencia' => 'SER-2025-002',
                'fotos' => ['rack1.jpg', 'rack2.jpg'],
                'documentos' => ['mantenimiento.pdf'],
                'precio' => 3500.00,
                'descripcion' => 'Mantenimiento mensual de servidores y red',
                'estado' => 'abierto',
                'fecha_prevista' => '2025-04-01',
                'fecha_finalizado' => null,
                'provincia' => 'Barcelona',
                'localidad' => 'Barcelona',
                'direccion' => 'Calle Tecnología 78',
                'postal' => '08001',
                'pais' => 'España',
                'latitud' => 41.3851,
                'longitud' => 2.1734,
                'telefono' => '678123457',
                'email' => 'it@empresa2.com',
                'empresa_id' => $empresa2->id,
            ]
        ];

        foreach ($tasks as $task) {
            Task::create($task);
        }
    }
}
